version: 2.1
jobs:
  build:
    working directory: /Desktop/BPMN-Sol
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test